#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Default values for user and group IDs
PUID=${PUID:-911}
PGID=${PGID:-911}
USERNAME=abc

# Check if the user already exists
if id -u "$USERNAME" >/dev/null 2>&1; then
    USERHOME=$(grep $USERNAME /etc/passwd | cut -d: -f6)
    usermod -d "/root" "$USERNAME"

    groupmod -o -g "$PGID" "$USERNAME"
    usermod -o -u "$PUID" "$USERNAME"

    usermod -d "$USERHOME" "$USERNAME"
fi

# Display branding information if available
if [[ -f /etc/s6-overlay/s6-rc.d/init-adduser/branding ]]; then
    cat /etc/s6-overlay/s6-rc.d/init-adduser/branding
elif [[ -f /run/branding ]]; then
    cat /run/branding
fi

# Optional: Display debug information
if [[ -f /app/ACW_RELEASE ]]; then
echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    '$(id -u "$USERNAME")'
User GID:    '$(id -g "$USERNAME")'
───────────────────────────────────────
Version Information
───────────────────────────────────────
Build version:    '$(cat /app/ACW_RELEASE)'
kepubify version: '$(cat /app/KEPUBIFY_RELEASE)'
Calibre version:  '$(cat /app/CALIBRE_RELEASE)'
───────────────────────────────────────'
else
echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    '$(id -u "$USERNAME")'
User GID:    '$(id -g "$USERNAME")'
───────────────────────────────────────'
fi

# Setting ownership rights for relevant directories
chown -R "$USERNAME":"$USERNAME" /app /config /defaults 2>/dev/null || true
