#!/bin/bash
# shellcheck shell=bash

# Default values for user and group IDs
PUID=${PUID:-911}
PGID=${PGID:-911}
USERNAME=abc

# Check if the user already exists
if ! id -u "$USERNAME" >/dev/null 2>&1; then
    USERHOME=$(grep $USERNAME /etc/passwd | cut -d: -f6)
    usermod -d "/root" "$USERNAME"

    groupmod -o -g "$PGID" "$USERNAME"
    usermod -o -u "$PUID" "$USERNAME"

    usermod -d "$USERHOME" "$USERNAME"
fi

# Display branding information if available
if [[ -f /etc/s6-overlay/s6-rc.d/init-adduser/branding ]]; then
    cat /etc/s6-overlay/s6-rc.d/init-adduser/branding
elif [[ -f /run/branding ]]; then
    cat /run/branding
fi

# Displaying UID and GID information
echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────
Benutzer UID:    '$(id -u "$USERNAME")'
Benutzer GID:    '$(id -g "$USERNAME")'
───────────────────────────────────────'

# Optional: Display build information if available
if [[ -f /etc/build_info ]]; then
    echo '
Build Information
───────────────────────────────────────
'
    cat /etc/build_info
    echo '
───────────────────────────────────────
'
fi

# Setzen der Eigentumsrechte für relevante Verzeichnisse
chown -R "$USERNAME":"$USERNAME" /app /config /defaults 2>/dev/null || true
