#!/bin/bash
# shellcheck shell=bash

# create symlinks for imagemagick policy.xml
rm -rf /etc/ImageMagick-6/policy.xml
ln -s /defaults/policy.xml /etc/ImageMagick-6/policy.xml

# create Google drive client_secrets.json file
if [[ ! -f /config/client_secrets.json ]]; then
    echo "{}" > /config/client_secrets.json
fi

# Pre-stage some files & directories for permissions purposes
mkdir -p /app/autocaliweb/cps/cache

# permissions
chown -R abc:abc \
    /config \
    /app/autocaliweb/cps/cache
